# Generated by Django 4.2 on 2023-05-22 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_content_post_contents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='contents',
            new_name='content',
        ),
    ]
